baseURL = "/"
theme = ["docsy"]
title = "GoTemplates.org"

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

enableGitInfo = true
enableMissingTranslationPlaceholders = true
enableRobotsTXT = true

pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsUseClassic = false
pygmentsStyle = "tango"

[deployment]
order = [".gif$", ".jpg$", ".png$", ".eot$", ".svg$", ".ttf$", ".woff$", ".woff2$", ".css$", ".js$"]

[[deployment.targets]]
name = "production"
cloudFrontDistributionID = "E3GETM50SYZZCQ"
URL = "s3://gotemplates.org?region=us-west-2"

[[deployment.targets]]
name = "staging"
cloudFrontDistributionID = "E35A9F0LJUFRID"
URL = "s3://preview.gotemplates.org?region=us-east-2"

[languages]
[languages.en]
title = "GoTemplates.org"
description = "Fall in love with Go templates."
languageName ="English"
weight = 1

[params]
copyright = "Stuart Jansen and Contributors"
#privacy_policy = "https://policies.google.com/privacy"

github_repo = "https://github.com/sjansen/gotemplates.org"
github_subdir = "site"

#gcs_engine_id = "TODO"

[[params.links.developer]]
name = "GitHub"
url = "https://github.com/sjansen/gotemplates.org"
icon = "fab fa-github"
desc = "Pull requests welcome!"

[params.mermaid]
enable = true
theme = "default"

[params.print]
disable_toc = false

[params.ui]
navbar_logo = true

[params.ui.feedback]
enable = true
yes = 'Glad to hear it! Please <a href="https://github.com/sjansen/gotemplates.org/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/sjansen/docsy/gotemplates.org/new">tell us how we can improve</a>.'

[params.ui.readingtime]
enable = true

[services.googleAnalytics]
id = "UA-185676782-1"
